/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mxnavi_platedetection_DetectionPlate */

#ifndef _Included_com_mxnavi_platedetection_DetectionPlate
#define _Included_com_mxnavi_platedetection_DetectionPlate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mxnavi_platedetection_DetectionPlate
 * Method:    nativeCreateObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_mxnavi_platedetection_DetectionPlate_nativeCreateObject
  (JNIEnv *, jclass);

/*
 * Class:     com_mxnavi_platedetection_DetectionPlate
 * Method:    nativeDestroyObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_mxnavi_platedetection_DetectionPlate_nativeDestroyObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_mxnavi_platedetection_DetectionPlate
 * Method:    nativeStart
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_mxnavi_platedetection_DetectionPlate_nativeStart
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_mxnavi_platedetection_DetectionPlate
 * Method:    nativeStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_mxnavi_platedetection_DetectionPlate_nativeStop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_mxnavi_platedetection_DetectionPlate
 * Method:    nativeSetFaceSize
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_mxnavi_platedetection_DetectionPlate_nativeSetFaceSize
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_mxnavi_platedetection_DetectionPlate
 * Method:    nativeDetect
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_mxnavi_platedetection_DetectionPlate_nativeDetect
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
